#!/bin/bash
uglify=$1
cs2o=$2
htmin=$3

calc() { awk "BEGIN { print $* }"; }

saved_js=0
saved_css=0
old_js=0
old_css=0

echo "build $(date)"

set -o errexit
# do js
js () {
  local md="js/min"
  paste --delimiter=\\n --serial vendor/js/jquery-3.2.1.min.js \
    vendor/js/bootstrap.min.js js/common.js js/goo.js js/verbs.js \
    js/writers.js js/index-helper.js js/forms/*.js js/viewers/*.js \
    vendor/js/platform.js > $md/index.js

  ${uglify:-uglifyjs} --mangle --ie8 --compress --source-map --output \
    $md/index.min.js -- $md/index.js

  old_js=$(wc -c < $md/index.js)
  rm $md/index.js
  new_js=$(wc -c < $md/index.min.js)
  saved_js=$((old_js - new_js))
  echo " !! built the javascript component to save $saved_js B = $(calc "$saved_js / $old_js * 100")%"
}

# do css
css () {
  local md="css/min"
  cat vendor/css/bootstrap.min.css vendor/css/raleway_playfair_display.css \
    css/common.css css/desktop.css css/mobile.css css/forms/*.css \
    css/viewers/*.css > $md/index.css

  ${cs2o:-csso} $md/index.css --map file --output $md/index.min.css

  old_css=$(wc -c < $md/index.css)
  rm $md/index.css
  new_css=$(wc -c < $md/index.min.css)
  saved_css=$((old_css - new_css))

  echo " !! built the stylesheet component to save $saved_css B = $(calc "$saved_css / $old_css * 100")%"
}

# do html
html () {
  ${htmin:-html-minifier} --html5 --collapse-whitespace \
    --collapse-inline-tag-whitespace --remove-style-link-type-attributes \
    --conservative-collapse --remove-script-type-attributes --remove-comments \
    index.big.html > index.html

  old_ml=$(wc -c < index.big.html)
  new_ml=$(wc -c < index.html)
  saved_ml=$((old_ml - new_ml))
  echo " !! built the  hypertext component to save $saved_ml B = $(calc "$saved_ml / $old_ml * 100")%"
}

js &
css &
html &
wait
echo "ended $(date)"
notify-send -i terminal "build complete" "$(date)"
# total_saved=$((saved_css + saved_js))
# total_uncmp=$((old_css + old_js))
# echo -e " !! built all components to save overall $total_saved B = $(calc "$total_saved / $total_uncmp * 100" )%\n"
