#!/bin/bash
uglify=$1
cs2o=$2

set -o errexit
# do js
cat js/common-funcs.js js/goo.js js/verbs.js js/writers.js \
  js/index-helper.js js/forms/edit-menu.js js/forms/edit-order.js \
  js/viewers/menu.js js/viewers/order.js > js/built/all_tmp_unc.js

${uglify:-uglifyjs} --compress --mangle --source-map --output js//built/all_compressed.js -- js/built/all_tmp_unc.js
echo built the javascript component

# do css
cat css/common.css css/desktop.css css/mobile.css css/forms/*.css css/viewers/*.css > css/built/all_tmp_unc.css
${cs2o:-csso} css/built/all_tmp_unc.css --map file --output css/built/all_compressed.css
echo built the stylesheet component
